### PR TITLE
Fix current stage bug in cleanup openstack script

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by p3ck** [comment]
This PR builds a new f29 container, you will need to rebase this on latest master to pick up your git change.

**Comment by 14rcole** [comment]
@p3ck I thought I would just need to rebase against the latest develop?

**Comment by p3ck** [comment]
> @p3ck I thought I would just need to rebase against the latest develop?

develop then.  I couldn't remember which branch was the latest merged code.

**Comment by p3ck** [comment]
@14rcole You can see that git is removed from f29 in this PR

-                   libselinux-python git \
+                   libselinux-python \

bad merge / rebase?

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
