### PR TITLE
Azure wrapper

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Added an Azure wrapper allowing user create a vm without creating all the virtual network virtual subnet

### CODE REVIEW

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by abraverm** [comment]
@JunqiZhang0, the change is too confusing (lines moved\removed\changed), can you minimize the change so it would be easy to review? I strongly recommend to squash the commits.

**Comment by samvarankashyap** [comment]
@JunqiZhang0 waiting on tests. 
LGTM

**Comment by JunqiZhang0** [comment]
[merge]

**Pull request merged**
