### PR TITLE
Added azure_nic test

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Added test

### CODE REVIEW

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
unit test failed https://jenkins-continuous-infra.apps.ci.centos.org/blue/rest/organizations/jenkins/pipelines/ci-linchpin-unittests/runs/2079/nodes/23/steps/29/log/?start=0

**Comment by JunqiZhang0** [comment]
@14rcole Hi Ryan, I have to revert your change for rundb to pass the test, the test was failed like the above link.

**Comment by abraverm** [comment]
I suggest squashing the changes and remove all the "required files" like rundb and requiremnet files - killing two birds with one stone.

**Comment by JunqiZhang0** [comment]
> I suggest squashing the changes and remove all the "required files" like rundb and requiremnet files - killing two birds with one stone.

will do

**Pull request closed without merging**
