### PR TITLE
Release version 1.9.1

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole #1515 #1516 #1518 
Should be reviewed and merged before the release.

**Comment by 14rcole** [comment]
Are we still waiting on #1516?

**Comment by samvarankashyap** [comment]
@14rcole We need not because it needs changes. We can push it since its not a necessary high priority feature right now.

**Comment by 14rcole** [comment]
[merge]

**Comment by samvarankashyap** [comment]
@14rcole Release job failed.

**Pull request merged**
