### PR TITLE
DNM: WIP : Port integration tests into python3

### LINKED ISSUE #1407: PORT integration tests into python3
**Is your feature request related to a problem? Please describe.**
Currently, all the tests run in python2.x 
Move all the integration tests into python3 for stronger support for python3.x 

**Additional context**
python 2.x support is being deprecated from version 1.9.0 
It would help if we move tests to python3 faster. 

Part of #283

### PR DESCRIPTION
**Pull request by samvarankashyap**
fixes #1407

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Blocked on #1409

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
Note: Centos 7 Does not have/support libselinux-python3 as per https://bugzilla.redhat.com/show_bug.cgi?id=1756015
which makes it difficult to support python3 on centos7 as for now. 
However, With centos8 released. We need to add centos8 support in integration tests
which in turn helps us in rhel8 support too.

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap what's the status of this PR?

**Comment by samvarankashyap** [comment]
PR no longer required. 
Since we already run integration tests on centos7, fedora 30 and fedora31

**Pull request closed without merging**
