### PR TITLE
Release linchpin 1.9.0.2

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject 
involves a fix that is causing sandbox violations on python3 virtual environments

### CODE REVIEW

**Comment by 14rcole** [comment]
We might as well wait until #1460 is merged to release this

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
closing in favor of 1.9.1  release

**Pull request closed without merging**
