### PR TITLE
RFR: remove ansible and gitpyhton pin ver

### PR DESCRIPTION
**Pull request by digitronik**
I found anisible version pin to `2.9.0`; after this we got small releases latest one is `2.9.6`. I don't thing pining ansible version its better option (it creates dependacy issues). lets provide compartibility of `~2.9`.

### CODE REVIEW

**Comment by 14rcole** [comment]
@samvarankashyap Do you remember why we pinned these in the first place?

**Comment by samvarankashyap** [comment]
@14rcole Yes. We pinned the version of ansible to control the version of ansible that is supported.

**Comment by digitronik** [comment]
@samvarankashyap @14rcole I agreed with `ansible>=2.7.1` but pining `<=2.9.0` I don't understand.
As per my basic testing linchpin working fine with `~2.9`; Its creating dependency issue to other dependent project.

**Comment by Dannyb48** [comment]
It looks like @14rcole filed MR #1736 remove the ansible restriction. 

The GitPython I think that was change to overcome a dependency mess between python2/3 gitpython and gitdb/gitdb2, @samvarankashyap ? 

@digitronik what version of python were you running and testing Linchpin that you saw issues with GitPython?

**Comment by digitronik** [comment]
@Dannyb48 I'm using python3.8.
I'm not facing any issue with `Git-python`.

I noticed it also pin like `ansible` on latest version so I removed it. If you check current version is `3.1.2`.

**Comment by digitronik** [comment]
@samvarankashyap @14rcole @Dannyb48 
This is the worst thing. I was requesting to remove ansible freeze from `Apr`. Maintainers participated in PR means well known about the issue. Without any suggestion or review same person opens new PR and other Merged :D LoL.

Btw, thanks for removing ansible pinning. closing this PR in a fever of #1736

**Comment by samvarankashyap** [comment]
@digitronik I am extremely sorry for your experience. 
The reason why your PR is not merged is due to a few internal issues and dependency errors caused by Gitpython. Which was mentioned by Danny in previous comments ...

**Pull request closed without merging**
