### PR TITLE
Fix combination beaker names and hosts

### PR DESCRIPTION
**Pull request by 14rcole**
Previously, each name was combined with each host.  This fixes the function so that each name is paired with the corresponding host

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Could you add sample unit test with mock data to check if works or not ?

**Comment by 14rcole** [comment]
@p3ck @samvarankashyap ptal

**Comment by 14rcole** [comment]
@samvarankashyap sorry, I didn't see your comment.  I can.  This would fall under #798 though, should I just put the unit test in there with the rest or slip it in here?

**Comment by samvarankashyap** [comment]
You can group it with others

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
