### PR TITLE
Fix rundb module for ansible 2.9.0

### PR DESCRIPTION
**Pull request by samvarankashyap**
moves all the rundb code into rundb ansible module to avoid errors in 
ansible 2.9.0 
fixes: #1458

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
Wasn't moving all of the code into one file supposed to help earlier?  Is this a known bug in Ansible 2.9 or anything?

**Comment by samvarankashyap** [comment]
@14rcole Moving all the rubdb code into single file and using it in module_utils helped, for 2.8.6. 
But with the recent release of ansible 2.9.0. 
Modules are no longer accepting the imports from external packages. Am not sure why.

**Comment by samvarankashyap** [comment]
@14rcole  
needs approval

**Comment by JunqiZhang0** [comment]
[MERGE]

**Comment by samvarankashyap** [comment]
[merge]

**Comment by 14rcole** [comment]
@samvarankashyap Is there any way we can roll back this change and merge #1460 instead?  That moves the rundb code to `module_utils`, which allows us to maintain separate files and makes my work with concurrency easier (since it involves supporting multiple providers).  I've tested it locally and it all works so far

**Pull request merged**
