### PR TITLE
Deduplicate tasks and fix env error in while provisioning volumes

### PR DESCRIPTION
**Pull request by samvarankashyap**
fixes: #878 
De-duplicate tasks with help of omit filter

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole I dont see any downstream tests running . Are they functional ??

**Comment by 14rcole** [comment]
@samvarankashyap https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin-messageBus-trigger/763/

**Comment by p3ck** [comment]
> @samvarankashyap https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin-messageBus-trigger/763/

That was triggered by me.  Seems to be running now, the power outage over the weekend might have messed up the work flow.  I'll keep an eye on it.

**Comment by samvarankashyap** [comment]
[test]

**Pull request merged**
