### PR TITLE
Add support for CentOS8 to linchpin

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
Beaker does not currently support CentOS 8.  This is something we'll have to mention in the next release notes when we announce CentOS 8 support

**Comment by 14rcole** [comment]
Fixes #1596

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap The tests failed while joining #linchpin after passing the ci-linchpin stage job
https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/ci-linchpin-container/detail/ci-linchpin-container/2587/pipeline

If you can sign this off I'm comfortable merging it

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
I wiped the centos8 builds from openshift and started again.  Hopefully this time whatever was being blocked will be unblocked

**Comment by samvarankashyap** [comment]
I think centos 8 testing is no longer required since we have "testing" for centos8  in github actions
Please re-open the PR if required.

**Pull request closed without merging**
