### PR TITLE
Esxi on libvirt

### PR DESCRIPTION
**Pull request by abraverm**

### CODE REVIEW

**Comment by abraverm** [comment]
depends on #1034

**Comment by abraverm** [comment]
FYI @ohochman, @RazTamir, @mcornea - this example shows how to deploy ESXi hypervisor on Libvirt (nested). This is preperation for #990, but maybe it could serve your needs for other things.

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by abraverm** [comment]
[merge]

**Pull request merged**
