### PR TITLE
Fix dict falling out of order in template rendering

### PR DESCRIPTION
**Pull request by 14rcole**
The _render_template() function converted an OrderedDict to a dict so that its templates could be rendered.  This converts the OrderedDict to a string to render the template so that key order is maintained until the data can be converted back to an OrderedDict

### CODE REVIEW

**Comment by 14rcole** [comment]
@lukas-bednar This should fix #540

**Comment by samvarankashyap** [comment]
@14rcole could you remove the debug statements before you merge . Thanks !

**Comment by 14rcole** [comment]
@samvarankashyap Will do

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
