### PR TITLE
fix and Update docker file, documentation

### LINKED ISSUE #1719: Error message showing up during linchpin container build
**Describe the bug**
When building the linchpin container as described in [this document](https://linchpin.readthedocs.io/en/latest/installation.html), the following error shows up on the container build log:

```
STEP 12: RUN curl -L -o /etc/...
...
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python2.7/site-packages (from google-auth->linchpin[beaker]) (0.2.8)
Requirement already satisfied: os-client-config>=1.28.0 in /usr/lib/python2.7/site-packages (from shade>=1.30.0->linchpin[beaker]) (2.0.0)
Collecting beaker-common
  Downloading beaker-common-27.4.tar.gz (33 kB)
Collecting lxml
  Downloading lxml-4.5.0-cp27-cp27mu-manylinux1_x86_64.whl (5.7 MB)
     |################################| 5.7 MB 4.9 MB/s 
Collecting PrettyTable
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Collecting gssapi
  Downloading gssapi-1.6.2.tar.gz (1.0 MB)
     |################################| 1.0 MB 18.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-JPJ_xT/gssapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-JPJ_xT/gssapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-JPJ_xT/gssapi/pip-egg-info
         cwd: /tmp/pip-install-JPJ_xT/gssapi/
    Complete output (11 lines):
    In distributed package, building from C files...
    /bin/sh: krb5-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-JPJ_xT/gssapi/setup.py", line 87, in <module>
        link_args = shlex.split(get_output('krb5-config --libs gssapi'))
      File "/tmp/pip-install-JPJ_xT/gssapi/setup.py", line 34, in get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/lib64/python2.7/subprocess.py", line 223, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
STEP 13: USER ${UID}
...
```

The build itself succeeds, but I suspect I ended up with a broken container.

**Additional context**

The build was done for a clone of the master branch.

### PR DESCRIPTION
**Pull request by samvarankashyap**
Updates linchpin dockerfile and documentation. 
fixes #1719

### CODE REVIEW

**Comment by Dannyb48** [comment]
@samvarankashyap I'm not seeing the `python-gssapi` rpm getting installed. I think Dockerfile issue might still be there

**Comment by samvarankashyap** [comment]
@Dannyb48 My bad i thought it was included as part of setup.py requirements. 
quick question is there pypi packaging available for python-gssapi ??

**Comment by Dannyb48** [comment]
@samvarankashyap Yeah, so originally we were installing the pypi packaging `python-gssapi` as part of the dependency requirements. But that was actually conflicting with the pypi package `gssapi` that the `beaker-commons` was installing. Provisioning would fail saying that certain libraries were missing/conflicting. It because prevelant when a user tried to use kinit for beaker auth. #1581 

Did some research and I found from the maintainers that python gssapi that `python-gssapi` should no longer be used, it is deprecated and no longer really maintained. They were recommending that everybody use `gssapi` because that is up to date and well maintained. Which is why I think the Beaker team is using it for the client. I modified the code to no longer install the `python-gssapi` package but I forgot to update the documentation to include the `python-gssapi` rpm.

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
