### PR TITLE
Update linchpin version to 1.6.5.rc1 to match version in release test

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject

### CODE REVIEW

**Comment by p3ck** [comment]
ignore paas-bot build 630.  That was from before @samvarankashyap rebased on develop.

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck : beaker failure .

**Comment by p3ck** [comment]
commit 613803333e1c83a13cfcd10f886c29cea434c2a9 broke beaker

**Comment by p3ck** [comment]
TASK [beaker : Initiating Provision of beaker resource group] ******************
fatal: [localhost]: FAILED! => {"reason": "'rescue' is not a valid attribute for a Task\n\nThe error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/beaker/tasks/provision_resource_group.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n  - name: \"provision beaker systems\"\n    ^ here\n\nThis error can be suppressed as a warning using the \"invalid_task_attribute_failed\" configuration"}
	to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/beaker.retry

**Comment by samvarankashyap** [comment]
@p3ck : but it passed before , is it something with ansible version ?

**Comment by p3ck** [comment]
ignore build 632.  new build with latest is in flight

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
