### PR TITLE
Update fedora30 container to python3

### PR DESCRIPTION
**Pull request by samvarankashyap**
Update the fedora30 container to python3
To be merged after #1491

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
Why not leave fedora 30 on python 2 so that we can test both python 2 and python 3 in the integration tests?

**Comment by samvarankashyap** [comment]
Sounds good. But we already do python2 testing on centos7.
with recent updates fedora and centos almost identical in terms of packages 
@14rcole

**Comment by 14rcole** [comment]
@samvarankashyap can we merge this?

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
