### PR TITLE
Libvirt VMs disks cache support

### PR DESCRIPTION
**Pull request by mcornea**
This change adds support for specifying the disk cache type for:
 - VM base image via disk_cache parameter
 - for each additional storage disk via cache parameter

### CODE REVIEW

**Comment by mcornea** [comment]
Depends on https://github.com/CentOS-PaaS-SIG/linchpin/pull/986

**Comment by mcornea** [comment]
@abraverm Hi! Could you please review this when you have a moment? Thanks!

**Comment by abraverm** [comment]
@mcornea, it would be nice if you add it to examples and documentation

**Comment by mcornea** [comment]
> @mcornea, it would be nice if you add it to examples and documentation

@abraverm sure, added.

**Comment by samvarankashyap** [comment]
@abraverm @mcornea you may merge it

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
