### PR TITLE
Add integration tests to Google cloud 

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary:
7b4336e6 Updated jenkins file references and tests to add gcloud integration tests
55771a72 Updated requirements of pycrypto for gcloud
88a1d461 Updated google cloud workspace examples

fixes: #858

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck The downstream tests are not triggered. Is it expected ?

**Comment by p3ck** [comment]
@samvarankashyap downstream jenkins fell over..  kicking it now.  I'll rebuild the failed job when it's ready.

**Comment by p3ck** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck @14rcole review

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
