### PR TITLE
Make beaker role OASIS-compatible and pass unit tests

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap The tests are hanging at the beaker mocktests.  Are they taking this long for other PRs?

**Comment by samvarankashyap** [comment]
@14rcole No. 
Other tests are running fine. 
which tests are we talking about ? Jenkins ci ?

**Comment by 14rcole** [comment]
@samvarankashyap The `run_beaker_mocktests.sh` script

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
