### PR TITLE
SSH command

### PR DESCRIPTION
**Pull request by abraverm**
User will able to ssh to provisioned systems based on latest inventory using SSH.
The command allows autocomplete (if enabled) for a simple search for potential targets.
If the target doesn't exist in the inventory, the user will get a list targets.

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@abraverm Could you please add little documentation within this PR ?

**Comment by 14rcole** [comment]
Looks great, can you squash your commits before you merge?

**Comment by abraverm** [comment]
fixes #873

**Pull request merged**
