### PR TITLE
Move rundb code to module_utils

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Sure i can revert the old commit. 
Let see if this PR passes tests. 
and we can merge it. 
I am assuming you have already tested with ansible 2.9.0 version.

**Comment by samvarankashyap** [comment]
@14rcole Instead of reverting you can rebase and resolve conflicts on this branch 
can we?
Since we already have working patch. We can always organize code with this PR.

**Comment by 14rcole** [comment]
@samvarankashyap done

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
