### PR TITLE
Cancel beaker job when there is a timeout while fetching the resources

### LINKED ISSUE #1153: Beaker job not cancelled if up is killed
**Describe the bug**
If you do a linchpin up to provision a machine in Beaker and that up command is killed, the Beaker job is left running. However, you will get no inventory back to work with it (which is probably expected). The bug is that even with the rundb, you cannot tear it down. Calling linchpin destroy with the resulting rundb will do nothing, so when using automation, the beaker job is just left alive until someone goes and manually kills it.

**To Reproduce**
1. Create a Jenkins job with say a 1h timeout
2. Create a pinfile with a beaker target that has a timeout >1h
3. Run the jenkins job that does a linchpin up
4. Let the job timeout
5. Even if you have it in a try catch with linchpin destroy, the beaker job is not cancelled

**Expected behavior**
The beaker job is cancelled

### PR DESCRIPTION
**Pull request by samvarankashyap**
fixes #1153 

Summary:
- added fetch_beaker_ids filter
- added unit test to fetch_beaker_ids
- Updated playbooks to handle timed out beaker resources

### CODE REVIEW

**Comment by johnbieren** [comment]
Looks fine to me, but I don't know the code in this PR as well as the others

**Comment by 14rcole** [comment]
@samvarankashyap when the cancel message is sent, does ansible wait for beaker to be finished cancelling the job or does it just send the message and continue?  If it's the former, is there any way to make this nonblocking?  It would seem silly to hit a timeout then have the user wait another 5-10 minutes because the job had  to be cancelled

**Comment by samvarankashyap** [comment]
> @samvarankashyap when the cancel message is sent, does ansible wait for beaker to be finished cancelling the job or does it just send the message and continue? If it's the former, is there any way to make this nonblocking? It would seem silly to hit a timeout then have the user wait another 5-10 minutes because the job had to be canceled.

@14rcole As far as my testing. Cancel message are instantaneous. I didn't face any blocking wait while the job is canceled. 
According to beaker module, we relay the beaker message and return.

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
