### PR TITLE
Replace os_hot_stack module with os_stack upstream ansible module 

### PR DESCRIPTION
**Pull request by samvarankashyap**
$Subject 
example:
#### topology
```yaml
---
topology_name: "dummy"
resource_groups:
  - resource_group_name: "hotstack"
    resource_group_type: "openstack"
    resource_definitions:
      - role: "os_heat"
        name: "test"
        template_path: "/home/srallaba/workspace/lp_ws/os_hot_stack/workspace/os_stack.yml"
        tag: "testtag"
    credentials:
      filename: clouds.yaml
      profile: default
```
#### os_stack file used:
```yaml
heat_template_version: 2013-05-23
description: Simple template to deploy a single compute instance
resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.small
      key_name: ci-factory
      networks:
        - network: e2e-openstack
```

Note: 

Inventory generation is not supported in either of the modules since openstack heat does not return the Ip address values of the instances created

### CODE REVIEW

**Comment by samvarankashyap** [comment]
fixes #326

**Comment by herlo** [comment]
@samvarankashyap Can you rebase this against the latest develop? Thanks!

**Comment by herlo** [comment]
@samvarankashyap can a test be written to show this passes?

**Comment by samvarankashyap** [comment]
@herlo Certainly , I have a workspace ready for the same . I this process i will also learn how to add tests to pipeline :+1:

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
