### PR TITLE
Allow repos and Packages to be installed

### PR DESCRIPTION
**Pull request by p3ck**
Fixes Issue: #651

### CODE REVIEW

**Comment by p3ck** [comment]
Still need to update the docs to reflect the new options in the next commit

**Comment by samvarankashyap** [comment]
@p3ck : could you please comment a example for beaker topology for testing the PR . Thanks !

**Comment by yashkmankad** [comment]
I ve asked Oksana (@anascko) to test and confirm this change in our workflow.
Thanks!

**Comment by p3ck** [comment]
example pin/topology file
`---
beaker-family:
  topology:
    topology_name: beaker-family
    resource_groups:
      - resource_group_name: "bkr-family"
        resource_group_type: beaker
        resource_definitions:
          - role: bkr_server
            # option to set job whiteboard message
            whiteboard: Provisioned with linchpin
            # options to configure amount of time spent polling beaker:
            # 60 attempts with 60 seconds wait time between them,
            # provisioning timeout is roughly 3600 seconds
            max_attempts: 240
            attempt_wait_time: 60
            # option to set cancellation message if linchpin cancels provisioning
            cancel_message: Job cancelled on account of rain
            recipesets:
              - family: RedHatEnterpriseLinux7
                tags:
                  - released
                name: rheltest
                arch: x86_64
                count: 1
                name: rhel7
                hostrequires:
                  - rawxml: '<hostlabcontroller op="=" value="lab-02.example.com"/>'
                repos:
                  - http://file.example.com/~bpeck/restraint/el7--test/
                install:
                  - restraint-debuginfo
`

**Comment by p3ck** [comment]
I spoke to @yashkmankad, I'm going to make one more update this and I can provide a test case as well.

**Comment by herlo** [comment]
@p3ck do you want this to be part of the [v1.6.2 release](https://github.com/CentOS-PaaS-SIG/linchpin/milestone/18)?

**Comment by p3ck** [comment]
Yes. Thank you for reminding me.

**Comment by p3ck** [comment]
I'll have a new pr by the end of Today

**Comment by p3ck** [comment]
[merge]

**Pull request merged**
