### PR TITLE
Inventory file can be defined in inventory_layout

### LINKED ISSUE #421: RFE: allow inventory file name be specified in layout file
A nice feature would be to specify the name of the inventory file in the layout file.

### PR DESCRIPTION
**Pull request by herlo**
Fixes #421 

Inventory can be specified in the 'inventory_layout' section of PinFile (or in separate layout file)

Documentation included to explain how to use it as part of the new advanced topics section.

### CODE REVIEW

**Comment by herlo** [comment]
[test]

**Comment by p3ck** [comment]
This has the old Jenkinsfile in this commit.  It says the PR is against develop, @herlo can you rebase and submit this again?

**Comment by herlo** [comment]
@p3ck all the tests pass now. :+1:

**Comment by herlo** [comment]
[merge]

**Comment by herlo** [comment]
[merge] let's try again

**Pull request merged**
