### PR TITLE
Disable gather_facts for faster execution

### PR DESCRIPTION
**Pull request by samvarankashyap**
Optimizing the playbook runs for speed : First attempt
$subject

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole @p3ck I wonder why the downstream tests were never triggered for this PR .

**Comment by p3ck** [comment]
@samvarankashyap we are looking into it.  It seems other groups have also missed fedmsg messages as well.

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
