### PR TITLE
Experiment to try to find a more reliable beaker install

### PR DESCRIPTION
**Pull request by p3ck**

### CODE REVIEW

**Comment by p3ck** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck 3/5 not bad :)

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
What do you mean by "more reliable"?  Is this to prevent the timeout issues we've been having?

**Comment by p3ck** [comment]
[merge]

**Pull request merged**
