### PR TITLE
Release linchpin version 1.9.0

### PR DESCRIPTION
**Pull request by samvarankashyap**
Release linchpin version 1.9.0

### CODE REVIEW

**Comment by 14rcole** [comment]
I'd recommend merging Danny's issue first.  Also, can we merge the ansible galaxy docs PR so that we can make that an experimental feature for 1.9?

**Comment by samvarankashyap** [comment]
@14rcole I agree. I will make sure. Ansible galaxy docs are in too.

**Comment by samvarankashyap** [comment]
Failed on 06_os_heat test on centos7 downstream. Rest all the tests pass.

**Comment by samvarankashyap** [comment]
@14rcole 
Need approval

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
