### PR TITLE
WIP Improved deep clean for multiple vm and fix the mock data issue 

### LINKED ISSUE #1692: The leftover of Azure should be cleaned
The leftover of Azure should be cleaned. Now it has leftover from multiple VM provisioning.

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Improved deep clean for multiple VM and fix the mock data issue. Should partially  #1681 and fix #1692

### CODE REVIEW

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by 14rcole** [comment]
@JunqiZhang0 is there an issue that you can link to this?

**Comment by JunqiZhang0** [comment]
[merge]

**Pull request merged**
