### PR TITLE
Release linchpin v2.0.1

### PR DESCRIPTION
**Pull request by samvarankashyap**
$SUBJECT
Release linchpin v2.0.1

### CODE REVIEW

**Comment by 14rcole** [comment]
Why 2.0.1 and not 2.1?

**Comment by samvarankashyap** [comment]
@14rcole since its a bug fix release

**Comment by samvarankashyap** [comment]
@14rcole since we are following semantic versioning and we do not have added functionalities 
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.

```

**Review by 14rcole — APPROVED** [review]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
