### PR TITLE
Minor modification to Dockerfile

### PR DESCRIPTION
**Pull request by samvarankashyap**
Minor modification to dockerfile to test the container tagging 
To be merged after #1166 is merged

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck 
Failing on Jenkinsunittestfile not found. 
 is there any other way we could disable unit tests this PR and  #1166 
https://jenkins-continuous-infra.apps.ci.centos.org/job/ci-linchpin-unittests/1271/console

**Comment by samvarankashyap** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck 
https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin-messageBus-trigger/59576/console

downstream is failing multiple times for the existing commit 93f199289f5e2c1fac0f2fa5a3f690ea59e316c1 
I tried rebuilding with parameters couple of times. It failed for 
https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin-container/1412/console at ci-linchpin container 

other reason :
```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/CentOS-PaaS-SIG/linchpin # timeout=10
Fetching upstream changes from https://github.com/CentOS-PaaS-SIG/linchpin
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/CentOS-PaaS-SIG/linchpin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/CentOS-PaaS-SIG/linchpin
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:143)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:271)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/CentOS-PaaS-SIG/linchpin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*" returned status code 137:
stdout: 
stderr: Unexpected end of command stream

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:860)
	... 8 more
ERROR: Error fetching remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE

```
what might be the reason for this?

**Comment by p3ck** [comment]
@samvarankashyap I would try cleaning out the workspace and/or restarting the jenkins master

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
Build process works correctly and the promotion of images happens.

**Pull request closed without merging**
