### PR TITLE
Adjust rundb module to make it backward compatible with Ansible versions < 2.9

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Failing on flake8

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole can we merge this?

**Comment by 14rcole** [comment]
Yes, the tests weren't running earlier but it looks like they've passed

**Comment by 14rcole** [comment]
[merge]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
