### PR TITLE
Ovirt support

### PR DESCRIPTION
**Pull request by machacekondra**
This PR add support for oVirt.

### CODE REVIEW

**Comment by machacekondra** [comment]
@mperina @oourfali @mykaul

**Comment by herlo** [comment]
hi @machacekondra. I'm sorry for the slow response as I've been on PTO for a while. I'll be reviewing this patch over the next few days. Thank you for submitting a patch for oVirt functionality. This is very exciting! :)

**Comment by herlo** [comment]
The first big hurdle is ansible 2.3.1. We need to do some extensive testing on all of the core providers. This isn't planned until next sprint at least.

**Comment by mykaul** [comment]
When's the next sprint planned?

**Comment by herlo** [comment]
We have sprints every 2 weeks. The next one starts July 26, 2017. If you have interest in testing out ansible 2.3+, we could use the help.

**Comment by herlo** [comment]
@machacekondra I've done some review and most things look good. Made a couple small changes so the code would pass CI tests. Can you provide output of this code running successfully in a comment here? I don't have an oVirt environment setup to test with at this time.

**Comment by machacekondra** [comment]
Topology:
```bash
omachace ~/linchpin_test $ cat topologies/example-topology.yml 
---
topology_name: "oVirt_vms_example_topology"
resource_groups: 
  - 
    resource_group_name: "mycirrosvm"
    resource_group_type: "ovirt"
    resource_definitions: 
      - 
        res_name: "1"
        res_type: "ovirt_vms"
        template: "cirros"
        cluster: "Default"
        memory: "1GiB"
      -
        res_name: "2"
        res_type: "ovirt_vms"
        template: "cirros"
        cluster: "Default"
        memory: "1GiB"

    credentials:
      filename: "ex_ovirt_creds.yml"
```

Layout:
```bash
omachace ~/linchpin_test $ cat layouts/example-layout.yml 
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 2
      host_groups:
        - example
```

Pinfile:
```bash
omachace ~/linchpin_test $ cat PinFile

example_target:
  topology: example-topology.yml
  layout: example-layout.yml

```

Credentials:
```bash
omachace ~/linchpin_test $ cat credentials/ex_ovirt_creds.yml 
---
# oVirt credentials example
default:
  ovirt_url: https://ondra.local:8443/ovirt-engine/api
  ovirt_username: admin@internal
  ovirt_password: 123456
```

Run:
```bash
omachace ~/linchpin_test $ linchpin --creds-path=/home/omachace/linchpin_test/credentials/ -vvvv up
from_api: True
calling: preup
hook preup initiated
 [WARNING]: Found variable using reserved name: check_mode

 [WARNING]: Found variable using reserved name: async


PLAY [schema check and Pre Provisioning Activities on topology_file] **********************************************************************************************************************************************

TASK [common : use linchpin_config if provided] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set lp_path] ***************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set lpconfig (linchpin.conf) full path] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set boolean evars from linchpin.conf] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set schema evars from linchpin.conf] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set default path evars from linchpin.conf] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set remaining evars from linchpin.conf] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : set default path evars using workspace var] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [common : if topology_file is passed, set topology to its value] *********************************************************************************************************************************************
skipping: [localhost]

TASK [common : if schema_file is passed, set schema to its value] *************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against the provided schema] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [common : assign output from provided schema] ****************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against schema_v3] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"output": "ValidationError: {u'resource_group_name': u'mycirrosvm', u'resource_definitions': [{u'res_name': u'1', u'res_type': u'ovirt_vms', u'memory': u'1GiB', u'template': u'cirros', u'cluster': u'Default'}, {u'res_name': u'2', u'res_type': u'ovirt_vms', u'memory': u'1GiB', u'template': u'cirros', u'cluster': u'Default'}], u'resource_group_type': u'ovirt', u'credentials': {u'filename': u'ex_ovirt_creds.yml'}} is not valid under any of the given schemas", "path": "/home/omachace/linchpin_test/topologies/example-topology.yml", "schema": "/usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/defaults/schemas/schema_v3.json"}}
...ignoring

TASK [common : Set state for schema_v3 validation] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [common : assign schema_v3 output] ***************************************************************************************************************************************************************************
skipping: [localhost]

TASK [common : check topology file against schema_v4] *************************************************************************************************************************************************************
ok: [localhost]

TASK [common : update output when schema_v4 is used] **************************************************************************************************************************************************************
ok: [localhost]

TASK [common : assign output from schema_v4] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [common : set fact for saving topology_job_ids] **************************************************************************************************************************************************************
ok: [localhost]

TASK [common : Get the resource group types defined in topology] **************************************************************************************************************************************************
ok: [localhost]

TASK [common : Filter resource_groups by type] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [common : Assigning facts with respect to their group type] **************************************************************************************************************************************************
ok: [localhost]

TASK [common : Registering resource group vars from topology] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [common : output vars] ***************************************************************************************************************************************************************************************
ok: [localhost]

PLAY [Provisioning resources based on resource group type] ********************************************************************************************************************************************************

TASK [dummy : DEBUG:: Dummy resource group list] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [dummy : declaring output vars] ******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [dummy : Initiating Provisioning of dummy resource group] ****************************************************************************************************************************************************

TASK [dummy : Initiating Teardown of dummy resource group] ********************************************************************************************************************************************************

TASK [openstack : declaring output vars] **************************************************************************************************************************************************************************
skipping: [localhost]

TASK [openstack : Initiating  Provisioning/Deprovioning of resources Openstack resource group] ********************************************************************************************************************

TASK [aws : Provisioning aws resources] ***************************************************************************************************************************************************************************
skipping: [localhost]

TASK [aws : declaring output vars] ********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [aws : Initiating  Provisioning of resources aws resource group] *********************************************************************************************************************************************

TASK [aws : Initiating  teardown of resources aws resource group] *************************************************************************************************************************************************

TASK [gcloud : DEBUG:: gcloud resource group list] ****************************************************************************************************************************************************************
skipping: [localhost]

TASK [gcloud : declaring output vars for topology outputs of gce] *************************************************************************************************************************************************
skipping: [localhost]

TASK [gcloud : Initiating  Provisioning of resources in gcloud resource group] ************************************************************************************************************************************

TASK [duffy : DEBUG:: Duffy resource group list] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [duffy : declaring output vars] ******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [duffy : Initiating Provisioning of duffy resource group] ****************************************************************************************************************************************************

TASK [duffy : Initiating Teardown of duffy resource group] ********************************************************************************************************************************************************

TASK [libvirt : Gather facts] *************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [libvirt : declaring output vars] ****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [libvirt : Initiating libvirt resource group] ****************************************************************************************************************************************************************

TASK [rackspace : DEBUG:: rackspace resource group list] **********************************************************************************************************************************************************
skipping: [localhost]

TASK [rackspace : declaring output vars] **************************************************************************************************************************************************************************
skipping: [localhost]

TASK [rackspace : Initiating  Provisioning/Deprovioning of resources rackspace resource group] ********************************************************************************************************************

TASK [beaker : allocate beaker outputs] ***************************************************************************************************************************************************************************
skipping: [localhost]

TASK [beaker : debug] *********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [beaker : provision beaker systems] **************************************************************************************************************************************************************************

TASK [beaker : fetch beaker details] ******************************************************************************************************************************************************************************

TASK [beaker : debug] *********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [beaker : append beaker outputs] *****************************************************************************************************************************************************************************

TASK [beaker : Initiating Teardown of beaker resource group] ******************************************************************************************************************************************************

TASK [openshift : allocate openshift output variables] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [openshift : provision openshift resources] ******************************************************************************************************************************************************************

TASK [ovirt : DEBUG:: oVirt resource group list] ******************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Currently Provisioning/Deprovisioning the resources under list ovirt_res_grps [{u'resource_group_name': u'mycirrosvm', u'resource_definitions': [{u'res_name': u'1', u'res_type': u'ovirt_vms', u'memory': u'1GiB', u'template': u'cirros', u'cluster': u'Default'}, {u'res_name': u'2', u'res_type': u'ovirt_vms', u'memory': u'1GiB', u'template': u'cirros', u'cluster': u'Default'}], u'resource_group_type': u'ovirt', u'credentials': {u'filename': u'ex_ovirt_creds.yml'}}]"
}

TASK [ovirt : Declaring output vars] ******************************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Initiating Provisioning/Deprovisioning of resources oVirt resource group] ***************************************************************************************************************************
included: /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_resource_group.yml for localhost

TASK [ovirt : Unset the authvar from previous run] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : set cred profile] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Get creds from auth driver] *************************************************************************************************************************************************************************
changed: [localhost]

TASK [ovirt : set auth_var] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Obtain SSO token with using username/password credentials] ******************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Provisioning resource definitions of current group] *************************************************************************************************************************************************
included: /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_res_defs.yml for localhost
included: /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_res_defs.yml for localhost

TASK [ovirt : Provision resources of type ovirt_vms] **************************************************************************************************************************************************************
 [WARNING]: While constructing a mapping from /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_ovirt_vms.yml, line 31, column 3, found a duplicate dict
key (when). Using last defined value only.

included: /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_ovirt_vms.yml for localhost

TASK [ovirt : Provision/deprovision ovirt_vms resources] **********************************************************************************************************************************************************
changed: [localhost]

TASK [ovirt : Append outputitem to topology_outputs] **************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Provision/deprovision ovirt_vms resources] **********************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt : Async:: save the job id] ****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt : Provision resources of type ovirt_vms] **************************************************************************************************************************************************************
included: /usr/lib/python2.7/site-packages/linchpin-1.0.2-py2.7.egg/linchpin/provision/roles/ovirt/tasks/provision_ovirt_vms.yml for localhost

TASK [ovirt : Provision/deprovision ovirt_vms resources] **********************************************************************************************************************************************************
changed: [localhost]

TASK [ovirt : Append outputitem to topology_outputs] **************************************************************************************************************************************************************
ok: [localhost]

TASK [ovirt : Provision/deprovision ovirt_vms resources] **********************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt : Async:: save the job id] ****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [ovirt : Always revoke the SSO token] ************************************************************************************************************************************************************************
ok: [localhost]

PLAY [Writing contents to file] ***********************************************************************************************************************************************************************************

TASK [output_writer : Updating topology_outputs] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [output_writer : Create output directories] ******************************************************************************************************************************************************************
ok: [localhost] => (item=/home/omachace/linchpin_test/resources)
ok: [localhost] => (item=/home/omachace/linchpin_test/inventories)

TASK [output_writer : Generate outputs when async is false] *******************************************************************************************************************************************************
changed: [localhost]

TASK [output_writer : Async:: Updating topology_outputs] **********************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : register var for async_outputs_os_server] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_os_obj] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_os_obj] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_os_server] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_aws_ec2] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_aws_ec2] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : register var for async_outputs_aws_ec2] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Wait on jobs] *******************************************************************************************************************************************************************************

TASK [output_writer : Async:: Updating topology_outputs after wait] ***********************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : Generate outputs when async is true] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [output_writer : set name of the resources_file for inventory generation] ************************************************************************************************************************************
ok: [localhost]

PLAY [inventory generation role] **********************************************************************************************************************************************************************************

TASK [inventory_gen : include_vars] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [inventory_gen : Updating topology_outputs] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [inventory_gen : Parse inventory layout as a ordered dict] ***************************************************************************************************************************************************
ok: [localhost]

TASK [inventory_gen : Updating inventory_path with the absolute path] *********************************************************************************************************************************************
ok: [localhost]

TASK [inventory_gen : Generate Generic Inventory] *****************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=35   changed=5    unreachable=0    failed=0   

Action 'up' on Target 'example_target' is complete
hook postup initiated
omachace ~/linchpin_test $ 
```

linchpin

**Comment by herlo** [comment]
You can merge this at your leisure. Thanks for the contribution. :)

**Comment by samvarankashyap** [comment]
@machacekondra

**Comment by machacekondra** [comment]
> @machacekondra

Is there anything else needed from me?

**Comment by herlo** [comment]
@machacekondra Clicking the 'merge pull request' button would be sufficient. If you want to add documentation, tests, and the like, it would be great. Thanks

**Comment by machacekondra** [comment]
> @machacekondra Clicking the 'merge pull request' button would be sufficient. If you want to add documentation, tests, and the like, it would be great. Thanks

I don't have permissions to merge :)

**Comment by herlo** [comment]
@machacekondra ah, I didn't realize. Merging now.

**Pull request merged**
