### PR TITLE
Make cfgs run when only certain targets are specified

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole PSI failure is due to a jenkins restart. 
You can re-trigger the tests from psi openshift console.

**Comment by johnbieren** [comment]
@mcornea fyi

**Comment by 14rcole** [comment]
@johnbieren If `cfgs` are in the PinFile but not listed in the targets, they will be parsed and applied to the layout when the inventory is generated.  Variables in `cfgs` will be applied to all targets in the layout with the proper resource group type

**Comment by johnbieren** [comment]
Ah, okay so the key under cfgs: has to match the resource group type. Great :+1:

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
