### PR TITLE
Fail on provider playbook failure while provisioning

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@p3ck Do we want to log it to console ?? when destroy fails, if thats the case linchpin already does the reporting.

**Comment by samvarankashyap** [comment]
@p3ck Current PR is a hard exit. However w.r.to destroy linchpin reports and continues with execution.

**Comment by johnbieren** [comment]
Commenting just so I get the emails for activity on this

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
