### PR TITLE
Add support for libvirt root disk type

### PR DESCRIPTION
**Pull request by mcornea**
- Allow using virtio-scsi driver for the VM root disk. 
 - Do not hard code controller number to allow creating more than one scsi disks
 - Re-use the same controller for storage and root disks when root disk is virtio-scsi

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@mcornea please rebase

**Comment by mcornea** [comment]
> Add to documentation:
> https://linchpin.readthedocs.io/en/latest/libvirt.html

Added.

**Comment by mcornea** [comment]
> @mcornea please rebase

Rebased.

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
