### PR TITLE
WIP: DNM Automate Linchpin Workspace Creation

### PR DESCRIPTION
**Pull request by skatlapa**

### CODE REVIEW

**Comment by skatlapa** [comment]
[test]

**Comment by skatlapa** [comment]
@samvarankashyap @14rcole could you take a quick look for anything obvious that you find? I am still testing this and will give an ack when its all clear

**Comment by skatlapa** [comment]
[test]

**Comment by samvarankashyap** [comment]
Moving to the backlog. shall be revisited again

**Pull request closed without merging**
