### PR TITLE
Updates to os_server module & additional volumes to os_server topologies

### LINKED ISSUE #329: Break out os_server2 into proper ansible module
It seems we bundle some libraries in linchpin that should really be bundled in another package. In this case, Ansible modules, should go into Ansible. This issue is to track getting os_server2 moved over.

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary:
- Replace os_server2 module with upstream Ansible os_server
- Added additional_volumes parameter to os_server topology supporting mount points
- Increase timeout for os_server provisioning
- fixes #329 #544

Example topology for testing: 
```yaml
---
topology_name: os-server-new
resource_groups:
  - resource_group_name: os-server-new
    resource_group_type: openstack
    resource_definitions:
      - name: "database"
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 2
        keypair: ci-factory
        fip_pool: 10.8.240.0
        additional_volumes:
          - name: "hello"
            size: 1
            device_name: "/dev/vdb"
        networks:
          - e2e-openstack
      - name: "frontend"
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 2
        keypair: ci-factory
        fip_pool: 10.8.240.0
        additional_volumes:
          - name: "hello"
            size: 1
            device_name: "/dev/vdb"
        networks:
          - e2e-openstack
    credentials:
      filename: clouds.yaml
      profile: ci-rhos
```

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@herlo @p3ck : Needs review and approval

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@herlo Last time it failed due to the quota issues.

**Comment by herlo** [comment]
[test] rerunning now that the instances are deleted.

**Comment by herlo** [comment]
[test]

**Comment by herlo** [comment]
[test]

**Comment by herlo** [comment]
[test]

**Comment by herlo** [comment]
Yay! It passes. Now for the actual review. :+1:

**Comment by herlo** [comment]
When using the following PinFile:

```
---
os-server-addl-vols:
  topology:
    topology_name: os-server-addl-vols
    resource_groups:
      - resource_group_name: os-server-addl-vols
        resource_group_type: openstack
        resource_definitions:
          - name: "database"
            role: os_server
            flavor: m1.small
            image: CentOS-7-x86_64-GenericCloud-1612
            count: 2
            keypair: ci-factory
            fip_pool: 10.8.240.0
            additional_volumes:
              - name: "hello"
                size: 1
                device_name: "/dev/vdb"
            networks:
              - e2e-openstack
        credentials:
          filename: clouds.yaml
          profile: ci-rhos
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        addl-vols-node:
          count: 2
          host_groups:
            - hello
```
I get the following error:

```
Error: [Errno 2] No such file or directory: u'/tmp/ws/os-server-addl-vols/inventories/os-server-addl-vols.inventory'
```
The inventory directory is not created. This feels like an error related to the previously merged #601.

**Comment by samvarankashyap** [comment]
##### linchpin up result 
```

TASK [gather_resources : Add inventory_path to outputs] **********************************************************************************************************************************************************
task path: /home/srallaba/workspace/lp_ws/os_server_update/linchpin/linchpin/provision/roles/gather_resources/tasks/main.yml:76
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "action": "up", 
            "conn_str": "/home/srallaba/.config/linchpin/rundb-220295150647999.json", 
            "db_type": "TinyRunDB", 
            "key": "outputs", 
            "operation": "update", 
            "run_id": 1, 
            "table": "os-server-addl-vols", 
            "value": "[{'inventory_path': ['/home/srallaba/workspace/lp_ws/os_server_update/workspace/inventories/os-server-addl-vols-881587.inventory']}]"
        }
    }, 
    "output": 1
}

PLAY RECAP *******************************************************************************************************************************************************************************************************
localhost                  : ok=31   changed=6    unreachable=0    failed=0   

Action 'up' on Target 'os-server-addl-vols' is complete
hook postinv initiated
hook postup initiated

ID: 16
Action: up

Target                  Run ID  uHash   Exit Code 
-------------------------------------------------
os-server-addl-vols          1  881587          0

(os_server_update) [srallaba@laptopy workspace]$ cat /home/srallaba/workspace/lp_ws/os_server_update/workspace/inventories/os-server-addl-vols-881587.inventory
[hello]
10.8.246.233 hostname=10.8.246.233
10.8.249.152 hostname=10.8.249.152

[all]
10.8.246.233 hostname=10.8.246.233
10.8.249.152 hostname=10.8.249.152
```

I unable not reproduce the same error ? Am i missing any thing ? 
Am using the same Pinfile you have sent me .

**Comment by samvarankashyap** [comment]
@herlo It seems that in your case the inventories directory is not found . Don't you think it should always be available in workspace ?

**Comment by herlo** [comment]
@samvarankashyap I don't think the inventory should *always* be available in the workspace, but that it should be created if necessary. And by necessary, I mean when someone provides an `inventory_layout` section in their PinFile. 

PS - I'm working on getting the trace for you.

**Comment by herlo** [comment]
small nit while I'm waiting for the linchpin up to finish.

I see this line and figure that's related to this PR, but I could be wrong:

```
TASK [openstack : generate res_def_names] ***************************************************************
task path: /home/herlo/Projects/centos/git/linch-pin/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:50
 [WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the
`loop_control` option for the task to something else to avoid variable collisions and unexpected
behavior.
```
Probably best to rename the loopvar.

**Comment by herlo** [comment]
@samvarankashyap The PinFile and output are in this [gist](https://gist.github.com/herlo/ffc7ec5deaa8de777555effbcbd8d6fd)

**Comment by samvarankashyap** [comment]
@herlo fixed the inventory dir issue with latest_commit

**Comment by herlo** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
