### PR TITLE
simple examples

### PR DESCRIPTION
**Pull request by abraverm**

### CODE REVIEW

**Comment by 14rcole** [comment]
As we begin adding use cases to `workspaces` that go beyond the generic provider-specific workspaces, I think we should be including a README.md in each workspace with a short description of the workspace and it's use case.  Can you add one to these workspaces?  I'll open an issue to add READMEs to existing ones

**Comment by abraverm** [comment]
Sure, sounds good :+1:

**Comment by 14rcole** [comment]
This is great, thank you

**Comment by abraverm** [comment]
[test]

**Comment by abraverm** [comment]
[merge]

**Pull request merged**
