### PR TITLE
Move inventory files into roles

### PR DESCRIPTION
**Pull request by 14rcole**
This PR moves the provider-specific inventory generation logic into each role, and updates the remaining inventory generation logic to search for `inventory.py` files therein.  This allows users to write their own roles without creating a linchpin PR for inventory generation.

I know this is a huge PR, but unfortunately none of it could be broken down into multiple commits.  Most of the changes are the result of moving the inventory files into the roles, but because of some necessary updates to things like import paths, git won't show it as just a moved file

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap #1409 is dependent on this

**Comment by samvarankashyap** [comment]
@14rcole I see the build is failing ...

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
