### PR TITLE
Release linchpin 1.9.1.1

### PR DESCRIPTION
**Pull request by samvarankashyap**
Release linchpin 1.9.1.1

### CODE REVIEW

**Comment by 14rcole** [comment]
What's been changed since 1.9.1?

**Comment by samvarankashyap** [comment]
@14rcole Needs approval

**Comment by samvarankashyap** [comment]
@14rcole There was a failure in release Job due to pytest runner requirement.

**Comment by samvarankashyap** [comment]
I had to fix it by #1523

**Comment by samvarankashyap** [comment]
@14rcole Lets make sure this release job succeeds.

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
