### PR TITLE
Remove unused functions from Inventory Filters

### PR DESCRIPTION
**Pull request by 14rcole**
Many of the provider-specific inventory filter functions are never used (and likely never will be) so there's no need to keep them around

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test] failures appear to be because of the openstack infrastructure

**Comment by samvarankashyap** [comment]
@14rcole I checked on openstack console. It seems unresponsive now. I would suggest you check the console from time to time.

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap Failures are once again network flakes.  I had a pass this morning.  Want to take another look at the PR before I merge?

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
