### PR TITLE
Replace contra-hdsl tests with travis-ci

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap Are we moving back to travis permanently?

**Comment by samvarankashyap** [comment]
@14rcole Yes for unit tests we are until we find a better and stable alternative

**Comment by samvarankashyap** [comment]
@p3ck Travis ci is already enabled for this repository and currently its running tests for every PR

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
