### PR TITLE
Made role Azure to OASIS standard

### LINKED ISSUE #1634: Make Azure role to oasis standard
Make Azure role to oasis standard

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Fix #1634

### CODE REVIEW

**Comment by 14rcole** [comment]
@junqizhang can you add the azure tests to github actions in the same way that aws was added for #1654?

**Comment by JunqiZhang0** [comment]
I had a separate pr for that,  I will merge this pr after that one gets merged @14rcole

**Comment by JunqiZhang0** [comment]
[test]

**Comment by samvarankashyap** [comment]
@JunqiZhang0 needs rebase

**Comment by JunqiZhang0** [comment]
[merge]

**Pull request merged**
