### PR TITLE
Add tutorial on how to use linchpin template data

### LINKED ISSUE #863: Tutorial: Add tutorial on how to use linchpin template data
$subject 
As a part of #757

### PR DESCRIPTION
**Pull request by 14rcole**
Resolves #863

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
