### PR TITLE
Fixed private image

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Fix CI, now we have our own private image without any leftover. @abraverm Could you please rebase this into your pr? It will fix the failing tests

### CODE REVIEW

**Comment by abraverm** [comment]
how do you generate the image?
Also something is blocking the CI from testing

**Comment by JunqiZhang0** [comment]
> how do you generate the image?
> Also something is blocking the CI from testing

I just manually created one for this moment, if there's a requirement of creating images, I'll go ahead to investigate that.

**Comment by abraverm** [comment]
[merge]

**Comment by abraverm** [comment]
I think we should have automation for image building as people tend to ask about it, but not critical for this pr.

**Pull request merged**
