### PR TITLE
Release version 1.7.2

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by p3ck** [comment]
failing in openstack.
```
    "msg": "Error creating security group rule: Client Error for url: https://ci-rhos.centralci.eng.rdu2.redhat.com:13696/v2.0/security-group-rules.json, Security group rule already exists. Rule id is 6585fd6d-e8dc-49ea-b911-4c365af1ebc3."
```

**Comment by samvarankashyap** [comment]
@p3ck 
```
Could not find a branch containing commit b67537369c1103d54ab1da6e8ced7d963b28ed83
[Pipeline] End of Pipeline
ERROR: No version b67537369c1103d54ab1da6e8ced7d963b28ed83 found for library linchpin-pipeline
Finished: FAILURE
```

**Comment by p3ck** [comment]
> @p3ck
> https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin-container/998/console
> 
> ```
> Could not find a branch containing commit b67537369c1103d54ab1da6e8ced7d963b28ed83
> [Pipeline] End of Pipeline
> ERROR: No version b67537369c1103d54ab1da6e8ced7d963b28ed83 found for library linchpin-pipeline
> Finished: FAILURE
> ```

Not unexpected when multiple force pushes have happened and this was queued for a while.  When it finally ran the commit was no longer there..

that is not the issue.. The issue is the openstack error I posted above.

**Comment by 14rcole** [comment]
@p3ck the first issue can be resolved with #983.  If we merge that I'll rerun the tests

**Comment by p3ck** [comment]
@14rcole So I only just noticed that you didn't do this as an RC.  This is the actual release of 1.7.2.  
Looks like #983 needs to be merged still. After that we should be good to go here right?

**Comment by 14rcole** [comment]
@p3ck Sorry, yes.  I believe that #982 needs to be merged as well, but it looks like it has been

**Comment by p3ck** [comment]
@14rcole looks like you have rebased now that the others are merged?  Just checking.

**Comment by 14rcole** [comment]
@p3ck yes

**Comment by p3ck** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole : rebase

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@p3ck @samvarankashyap good to merge?

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
