### PR TITLE
Release 1.6.5

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject

### CODE REVIEW

**Comment by 14rcole** [comment]
@samvarankashyap tests failed.  Looks like a timeout waiting for an fip in openstack

**Comment by samvarankashyap** [comment]
@14rcole cleaned up instances. Retrying again

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole @p3ck SUCCESS

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
