### PR TITLE
Updated resource_names with prefix ci-lp-cp-

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject 

Update resource names to easily identify the provisioned resources.

### CODE REVIEW

**Comment by 14rcole** [comment]
This may be better suited to a different PR, but do we want to change the default values for credentials?   `clouds.yaml` is a pretty generic name for an OpenStack creds file, but if we change it to `continuous-productization.yaml` we won't have to supply template data to our integration tests

**Comment by samvarankashyap** [comment]
@14cole : 
We can just upload the credentials to jenkins with the ci-rhos profile and clouds.yaml filename. Hence we need not change. 
Does that sound good ?

**Comment by 14rcole** [comment]
@samvarankashyap That works for me

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
