### PR TITLE
Update flags ordering and add metavars

### LINKED ISSUE #724: linchpin fails to provision in openstack with error "TypeError: up() got an unexpected keyword argument 'ignore_failed_hooks'"
```
Traceback (most recent call last):
  File "/opt/linchpin_dir/bin/linchpin", line 11, in <module>
    load_entry_point('linchpin==1.6.2', 'console_scripts', 'linchpin')()
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/linchpin_dir/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: up() got an unexpected keyword argument 'ignore_failed_hooks'

```
The above is the traceback i received when i ran 
```
linchpin -v -w /tmp/pnq --creds-path /tmp/pnq/credentials/ up"
```

Below is the topology file

```
topology_name: openstack_topo
resource_groups:
- resource_group_name: master
  resource_group_type: openstack
  resource_definitions:
  - name: 4284.testrelm.test
    type: os_server
    flavor: m1.small
    image: Fedora-Cloud-Base-26-compose-latest
    keypair: mniranja_linchpin
    count: 1
    networks:
    - idm-jenkins
    fip_pool: 10.8.240.0
  credentials:
    filename: clouds.yaml
    profile: devstack
```

 example-layout.yml 
```
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    master:
      count: 1
      host_groups:
      - master
      - sut
```

PinFile:
```
---
example_target:
  topology: example-topology.yml
  layout: example-layout.yml
```

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject
fixes #724

### CODE REVIEW

**Comment by herlo** [comment]
@samvarankashyap while this resolves the issue, I'm not sure we should update the requirement. Specifically because we can update the option signatures to include that third variable which can be used to define the value passed to the function.

Consider the following as a more complete solution:

```
@click.option('-o', '--output-file', '--output-pinfile', 'outfile',
              metavar='OUTPUT_FILE',
              help='Write out PinFile to provided location')
@pass_context
def runcli(ctx, outfile):
.. snip ..
```
As with other fixes recently put in place for `--ignore-failed-hooks`, shortened to `--ifh`), the third argument in the above option decorator could be used with the up/destroy methods.

```
@click.option('--ignore-failed-hooks', '--ifh' , 'ignore_failed_hooks')
@pass_context
def up(ctx, ignore_failed_hooks):
```

Even if we do update Click to 7.0, this seems like a good plan going forward.

**Comment by samvarankashyap** [comment]
@herlo I agree with your suggested changes. Make more sense to the existing environments. 
Made changes accordingly.

**Comment by samvarankashyap** [comment]
@herlo : https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin/390/console

**Comment by herlo** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
