### PR TITLE
Add support for molecule converge tests to dummy and run tests on gthub actions

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by abraverm** [comment]
Where can I see the coverage results (percentage)?

**Comment by 14rcole** [comment]
@samvarankashyap PTAL

**Comment by 14rcole** [comment]
@abraverm If you go to one of the stages that says `multicontainer Testing on container matrix`, there's a step right after the unit tests that says `Report on code coverage`.  This will also fail if the coverage drops below 70%.  Hopefully we can increase that as we add more tests

**Comment by 14rcole** [comment]
The code coverage within github actions is 75%, but when I run it locally I get 70%.  I don't know why there's a difference

**Comment by 14rcole** [comment]
nvm, on github actions it was counting the unit tests as covered code.  That's fixed now

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
