### PR TITLE
Test Patch: update code to support Python2.x and Python3.x

### PR DESCRIPTION
**Pull request by samvarankashyap**
Test by updating linchpin/__init__

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole @p3ck: any thoughts? I used python-modernize to update code to be compatible with both python2.x and python3.x. Further, I changed the requirments.txt to use only python3 compatible package version.

**Comment by 14rcole** [comment]
@samvarankashyap Do we run integration tests in both python2 and python3?

**Comment by samvarankashyap** [comment]
@14rcole Ideally we should do it both , maybe in a seperate container. This patch makes sure that linchpin python based files are compatible with both 2.x and 3.x

**Comment by 14rcole** [comment]
Given the size of this PR, let's add a python 3 in a separate container, but make it a priority so we can (maybe) claim to be python3 compatible by the next release

**Comment by samvarankashyap** [comment]
@14rcole @p3ck If I merge it through *merge* command on comment will it be merging to develop branch or version-2.0 branch. Do container promotions happen with the other branch merges. If so, I can close this PR and create the same PR towards develop branch making the release 3.0 compatible. 
Note: It supports 2.7.x too.

**Comment by p3ck** [comment]
@samvarankashyap I believe it will merge into version-2.0 since that is what you made the PR for.

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
