### PR TITLE
Remove local fetch and simplify git and web directory cases

### LINKED ISSUE #699: Fetch protocol detection disabled
Linchpin 1.6.2 fetch defaults to git on Click level, in `shell/__init__.py` line 323:
`@click.option('--protocol', 'fetch_protocol', default='git',` 

While older version (1.5.x) detected protocol from URI first, in `cli/__init__.py` line 780- 792:
```
        protocol = fetch_protocol
        if protocol is None:
            self.ctx.log_state('detecting uri type')
            protocol_regex = OrderedDict([
                ('((git|ssh|http(s)?)|(git@[\w\.]+))'
                    '(:(//)?)([\w\.@\:/\-~]+)(\.git)(/)?',
                    'FetchGit'),
                ('^(http|https)://', 'FetchHttp'),
                ('^(file)://', 'FetchLocal')
            ])
            for regex, obj in protocol_regex.items():
                if re.match(regex, src):
                    fetch_protocol = obj
                    break

        if protocol is None:  # assume fetch_protocol is git if None
            protocol = 'FetchGit'

```
I suggest remove `default='git'`

### PR DESCRIPTION
**Pull request by abraverm**
Fix #699 and #698

### CODE REVIEW

**Comment by skatlapa** [comment]
[test]

**Comment by p3ck** [comment]
Update the PR based on the results of the unit tests please.

```yaml
    "stdout_lines": [
        "./linchpin/cli/__init__.py:4:1: F401 're' imported but unused", 
        "./linchpin/cli/__init__.py:802:45: E128 continuation line under-indented for visual indent", 
        "./linchpin/cli/__init__.py:803:45: E128 continuation line under-indented for visual indent", 
        "./linchpin/cli/__init__.py:804:45: E128 continuation line under-indented for visual indent"
    ]
```

**Comment by skatlapa** [comment]
If I see it right, we might be running into [1]. We need to set to head I believe, but not fully sure.

[1] - https://github.com/NixOS/nix/pull/1927

**Comment by skatlapa** [comment]
pardon ignore above, I see its head by default anyways

**Comment by abraverm** [comment]
@p3ck,  Jenkins reported success and I didn't think I need to dig through 3(or more?) layers of builds, also I don't see any information about how to run part\all tests locally. The [Testing section](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/CONTRIBUTING.rst#testing) seems to be out of date (there is no .travis) and running `python setup.py test` produces too many issues to be relevant `failed, 79 passed, 3 deselected, 669 warnings`. In any case, I've fixed the warnings you mentationed but I don't know where you found them.

**Comment by p3ck** [comment]
@abraverm I understand the confusion.  Because we have upstream and downstream jenkins instances it isn't very clear.  

Upstream jenkins uses the github pull request trigger and is reported in the All Checks section.  But downstream jenkins which is inside the firewall is triggered via the Fedora Message Bus and can only report results here as comments.  And it only comments when it finishes running.

Even without the above the workflow is complicated.  We first have to see if any containers need to be rebuilt for the PR and then run the actual tests.  That means we have three levels of jobs.  Trigger -> Containers -> Testing.  You may have to traverse to the testing job to see the actual errors.

This has grown organically and probably could use some fresh eyes on it.

**Pull request merged**
