### PR TITLE
Fix bug causing provisioning to hang and preventing hooks from being run

### LINKED ISSUE #1263: Shell Hooks do not run on target machines with ansible 2.8
**Describe the bug**
Hooks do not run on target machines in linchpin with ansible>=2.8.  For some ansible uses localhost as the inventory and attempts to run all steps on the local machine

**To Reproduce**
1. Run a linchpin workspace with hooks

**Expected behavior**
Postup hooks are run on target machine

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue

**Additional context**
I discovered this because I was running Silverblue, which does not include yum or dnf.  It may be hard to troubleshoot on other machines

### PR DESCRIPTION
**Pull request by 14rcole**
Fixes #1263

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole I have approved the pull request but I see, the linchpin is getting hung on unit tests.

**Comment by samvarankashyap** [comment]
@14rcole needs rebase

**Comment by samvarankashyap** [comment]
@14rcole failing on tests

**Comment by samvarankashyap** [comment]
@14rcole rebase should fix the erros

**Comment by Dannyb48** [comment]
@14rcole are you able to rebase your code and test so that this can be merged?

**Comment by Dannyb48** [comment]
@14rcole are you able to re-base and test this again?

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@Dannyb48 Some of the tests are being skipped, but I'm confident that this is non-breaking.  I'm just going to merge it

**Comment by 14rcole** [comment]
[merge]

**Comment by abraverm** [comment]
This didn't solve the problem, the tests are not skipped but timed out. 
@Dannyb48 , @JunqiZhang0  Later PRs also failed because of it but some were merged

**Comment by JunqiZhang0** [comment]
@abraverm Did you try within virtualenv? Sometimes the problem comes from the localhost, just a reminder.

**Comment by abraverm** [comment]
@JunqiZhang0, for local development I use virtualenv and the problem is solved. The CI has the final word about it, and if you have a local issue then try to reproduce it before applying fixes.

**Pull request merged**
