### PR TITLE
Libvirt differentiate ip

### LINKED ISSUE #1248: When Libvirt instances have multiple IPs it would be great to label which is public vs private
**Is your feature request related to a problem? Please describe.**

Since libvirt instances can be attached to multiple networks, That would mean multiple IPs are collected and stored by Linchpin. It would be great if Linchpin could differentiate between which IP is 'public' and which is 'private' like the other providers (OpenStack/AWS). This is beneficial to know so that the correct IP is being used later in an inventory with Ansible or something post-provisioning usage. 

**Describe the solution you'd like**

I think this might have to be built into the libvirt playbooks. In libvirt a private network is one without the **forward** element[1] in the network.

Maybe add another task that queries the networks and checks for this element. Then save a temp variable that contains a map which notes which is private and public. Which can be used later When building the IP address list for each VM/instance

[1] https://libvirt.org/formatnetwork.html#examplesPrivate

**Describe alternatives you've considered**

The other alternative would for a user or some other tool consuming Linchpin (i.e. carbon) to build this extra step into their framework.

### PR DESCRIPTION
**Pull request by JunqiZhang0**
Fix #1248

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@JunqiZhang0 
Failed unit tests
```
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2019-08-19 15:05:34.495968", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "./linchpin/FilterUtils/FilterUtils.py:22:1: E302 expected 2 blank lines, found 1\n./linchpin/FilterUtils/FilterUtils.py:28:1: E302 expected 2 blank lines, found 1", 
    "stdout_lines": [
        "./linchpin/FilterUtils/FilterUtils.py:22:1: E302 expected 2 blank lines, found 1", 
        "./linchpin/FilterUtils/FilterUtils.py:28:1: E302 expected 2 blank lines, found 1"
    ]
} 
```

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[test]

**Comment by JunqiZhang0** [comment]
[merge]

**Pull request merged**
