### PR TITLE
Progress Bar and multiprocessing

### PR DESCRIPTION
**Pull request by abraverm**
This change includes number of new features:
 - Progress bar (tqdm) that shows Linchpin provisioning process (PinFile -> resource group -> resource). It also includes status update that it recieves from the resource in Ansible.
 - Message bus (zmq) between Ansible and Linchpin - messages can be sent from Ansible to and from Linchpin during its execution which allows Linchpin to do something else during Ansible run (such as progress bar update).
 - Multiprocessing of Linchpin and Ansible make it possible to update the progress bar.

Custom Ansible action plugins were added for specific provisioning resources which take the longest time during Linchpin execution. To trigger on specific task, a callback plugin could be used but I didn't add it to the PR as there is little use for it (maybe for a smoother progress bar...)

Examples:
[asciicast](https://asciinema.org/a/RsdwOGUSKen3WIuW3OcKPbm2I)

[asciicast](https://asciinema.org/a/YVW1DoHiD2CAE7GUFTS1ScvsJ)

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@abraverm needs rebase

**Comment by abraverm** [comment]
[test]

**Comment by abraverm** [comment]
[test]

**Comment by 14rcole** [comment]
@abraverm This looks great!  Can you record a demo with beaker?  I want to see what happens in a really long task.  Also, what happens when you specify some level of verbosity?

**Comment by abraverm** [comment]
Level verbosity will end up the same as before (ansible log) and I wonder how\if the new UI should support it, ideas?
Beaker detailed progress is not yet developed, as I wanted a fast development process and an MVP, I think I will do it in another PR.

What do you think of the implementation if we merge it as is?

**Comment by Dannyb48** [comment]
So is the multiprocessing in place only to enable the async communication between ansible and linchpin for progress bar displaying?

**Comment by samvarankashyap** [comment]
[test]

**Comment by abraverm** [comment]
> So is the multiprocessing in place only to enable the async communication between ansible and linchpin for progress bar displaying?

Yes, but I think its a stepping stone for parallel provisionining of resources and groups, and maybe for other features too.

**Comment by abraverm** [comment]
[test]

**Comment by abraverm** [comment]
@samvarankashyap  @14rcole , the test fails on something unrelated:
```
"ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel",
```

**Comment by abraverm** [comment]
[test]

**Comment by abraverm** [comment]
@samvarankashyap, @14rcole  please review the PR

**Comment by abraverm** [comment]
ping

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
