### PR TITLE
little cleanups..

### PR DESCRIPTION
**Pull request by p3ck**
drop rpm version of ansible for centos7
 - epel7 has ansible2.5

### CODE REVIEW

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by p3ck** [comment]
[test]

**Comment by herlo** [comment]
@p3ck I think I saw that you added these fixes into your latest Jenkins updates. Can we close this PR?

**Comment by p3ck** [comment]
well..  yes, it was added to Jenkinsfile, but the other files are still the same.  But this is pretty stale now so I'll close it

**Pull request closed without merging**
