### PR TITLE
WIP: Fix SELinux failure in CentOS7 container

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
Putting this on hold until libvirt tests are ported to a privileged container

**Comment by samvarankashyap** [comment]
closed in favor of #1328

**Pull request closed without merging**
