### PR TITLE
more variables in examples

### PR DESCRIPTION
**Pull request by abraverm**
To allow easy downstream testing by other teams of upstream examples

### CODE REVIEW

**Comment by abraverm** [comment]
I don't know what is the right way of doing things here - PR shouldn't hold another PR for so long (IMHO) but what's the point of the change if it will be replaced completely by the other PR. At  this point I think it all depends on timing and how much the example will be changed. I mean if this PR Openshift example is still mostly usable and require minor adjustments then lets merge it and update #783.

**Comment by skatlapa** [comment]
I agree, will do that, @samvarankashyap sounds good re 783?

**Comment by abraverm** [comment]
@skatlapa, the last Jenkins failure doesn't seem to be related to the openshift example changes:
```
TASK [openshift : List all the pods] *******************************************
task path: /usr/lib/python2.7/site-packages/linchpin/provision/roles/openshift/tasks/provision_openshift.yml:30
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py", line 176, in <module>
  File "/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py", line 172, in main
  File "/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py", line 153, in execute_module
  File "/tmp/ansible_k8s_facts_payload_6tlp37/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py", line 207, in kubernetes_facts
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 43, in inner
    raise api_exception(e)
openshift.dynamic.exceptions.BadRequestError: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Content-Type': 'text/plain; charset=utf-8'})
HTTP response body: 400 Bad Request
Original traceback: 
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 41, in inner
    resp = func(self, resource, *args, **kwargs)

  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 168, in get
    return self.request('get', path, **kwargs)

  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 309, in request
    _return_http_data_only=params.get('_return_http_data_only', True)

  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)

  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)

  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)

  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)

  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1543398035.92-208305189686564/AnsiballZ_k8s_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py\", line 176, in <module>\n  File \"/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py\", line 172, in main\n  File \"/tmp/ansible_k8s_facts_payload_6tlp37/__main__.py\", line 153, in execute_module\n  File \"/tmp/ansible_k8s_facts_payload_6tlp37/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py\", line 207, in kubernetes_facts\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 43, in inner\n    raise api_exception(e)\nopenshift.dynamic.exceptions.BadRequestError: 400\nReason: Bad Request\nHTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Content-Type': 'text/plain; charset=utf-8'})\nHTTP response body: 400 Bad Request\nOriginal traceback: \n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 41, in inner\n    resp = func(self, resource, *args, **kwargs)\n\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 168, in get\n    return self.request('get', path, **kwargs)\n\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 309, in request\n    _return_http_data_only=params.get('_return_http_data_only', True)\n\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 155, in __call_api\n    _request_timeout=_request_timeout)\n\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 342, in request\n    headers=headers)\n\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 231, in GET\n    query_params=query_params)\n\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 222, in request\n    raise ApiException(http_resp=r)\n\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```
https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin/531/artifact/linchpin/fedora27_logs/openshift.log

**Comment by samvarankashyap** [comment]
@abraverm could you rebase against develop please .

**Comment by abraverm** [comment]
@samvarankashyap, same error

**Comment by samvarankashyap** [comment]
@abraverm : could you exclude openshift examples in this PR . 
Further , Please create a seperate PR for openshift examples update for easier troubleshooting.

**Comment by samvarankashyap** [comment]
[merge]

**Comment by abraverm** [comment]
#816

**Pull request merged**
