### PR TITLE
Make container image changes necessary to run openstack cleanup nightly

### PR DESCRIPTION
**Pull request by 14rcole**
This will allow the `linchpin-nightly` pipeline to clean up the instances

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap I know, for some reason the linchpin command can't be found

**Comment by samvarankashyap** [comment]
@14rcole the above usually happens when container builds are broken or linchpin installation inside the container fails

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
