### PR TITLE
Make integration tests use linchpin fetch

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap this looks like it's also failing due to the aws_ec2_eip quota.  Should I manually disable the test or just ignore the failure?

**Comment by 14rcole** [comment]
[merge]

**Comment by samvarankashyap** [comment]
@14rcole let's disable the test. I see the merge failed too.

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
