### PR TITLE
Move getChangedFile function to utils

### LINKED ISSUE #693: Move getChangedFile into LinchpinPipelineUtils.groovy
In the recent updates to the merge and release process, a new function was introduced in  [JenkinsfileGHPRMerge]https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/config/Dockerfiles/JenkinsfileGHPRMerge#L159). 

It was recommended in PR #685 to move this into LinchpinPipelineUtils.groovy and refactor the getTargetsToTest method also. This ticket is here to track that work.

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject
fixes #693

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
I think the PR needs rebase

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@samvarankashyap Needs to be investigated for test timeouts. 
might need to rebase ??

**Comment by samvarankashyap** [comment]
[merge]

**Comment by samvarankashyap** [comment]
@p3ck @
failed on 
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 32: unable to resolve class org.centos.pipeline.LinchpinPipelineUtils
 @ line 32, column 1.
   import org.centos.pipeline.LinchpinPipelineUtils
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:131)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:560)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:521)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

```

am I doing something wrong? 
+adding @14rcole @johnbieren

**Comment by johnbieren** [comment]
I do not recommend checking out the shared library with the import like you have here

**Comment by samvarankashyap** [comment]
> I do not recommend checking out the shared library with the import like you have here

@johnbieren What would be the correct way?

**Comment by johnbieren** [comment]
@samvarankashyap The stuff starting around line 20 are the proper library checkouts (in the Jenkinsfile)

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
