### PR TITLE
Add fedora30 to container list

### LINKED ISSUE #1124: RFE: Add fedora30 to integration tests
Since Fedora 30 is released. It would be great if we could include it for integration tests inside linchpin.

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject
work in progress
Add fedora30 to container list and update references in Jenkins files
fix #1124

### CODE REVIEW

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
@p3ck Am I missing something in adding fedora30 container, I see the build is successful but the build job hangs up forever. 
Please review it. 
thanks

**Comment by p3ck** [comment]
@samvarankashyap need to update the tag for fedora30 container to use 30

**Comment by samvarankashyap** [comment]
@p3ck @14rcole : Needs review

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
