### PR TITLE
Fix issue #960

### PR DESCRIPTION
**Pull request by mcornea**
This change implements the following changes:

 - register res_count var as a list by using with_sequence. Previously
   the res_count var was registered as a shell task output which made
   res_count.stdout a string and didn't allow iterating over the items
   in the list.

 - store output_name var as a list allowing iteration over multiple
   elements. Previously only the last iteration item was stored in the
   output_name.

### CODE REVIEW

**Comment by mcornea** [comment]
Fixes #960

**Comment by samvarankashyap** [comment]
@mcornea Could you please squash commits into one commit before we merge it . Thank you :+1:

**Comment by mcornea** [comment]
@samvarankashyap Commits are now squashed.

**Comment by 14rcole** [comment]
@mcornea Thanks for fixing this! [merge]

**Pull request merged**
