### PR TITLE
Add support for providing dnsmasq options to libvirt network definition

### PR DESCRIPTION
**Pull request by mcornea**
Introduce the ability to pass dnsmasq options to the libvirt network definition.

### CODE REVIEW

**Comment by 14rcole** [comment]
@samvarankashyap Do we need to wait to merge this until libvirt tests are re-enabled upstream?

**Comment by samvarankashyap** [comment]
@14rcole We can merge it. 
Since, It's not a major change.

**Comment by 14rcole** [comment]
@samvarankashyap but we can't verify that it works and doesn't break anything else

@mcornea Are you able to provision libvirt instances with linchpin 1.9.1?

**Comment by mcornea** [comment]
> @samvarankashyap but we can't verify that it works and doesn't break anything else
> 
> @mcornea Are you able to provision libvirt instances with linchpin 1.9.1?

Yes, it works for me:

```shell
[root@sealusa2 ~]# virsh net-dumpxml baremetal 
<network xmlns:dnsmasq='http://libvirt.org/schemas/network/dnsmasq/1.0' ipv6='yes'>
  <name>baremetal</name>
  <uuid>40f41aa6-e693-4fd9-94c0-72169accab6d</uuid>
  <forward mode='nat'/>
  <bridge name='baremetal' stp='on' delay='0'/>
  <mac address='52:54:00:39:c8:7b'/>
  <domain name='ocp-edge-cluster.qe.lab.redhat.com' localOnly='yes'/>
  <dns>
    <forwarder domain='apps.ocp-edge-cluster.qe.lab.redhat.com' addr='127.0.0.1'/>
    <host ip='fd2e:6f44:5dd8:c956::5'>
      <hostname>api</hostname>
      <hostname>api-int</hostname>
    </host>
    <host ip='fd2e:6f44:5dd8:c956::125'>
      <hostname>registry.ocp-edge-cluster.qe.lab.redhat.com</hostname>
    </host>
  </dns>
  <ip family='ipv6' address='fd2e:6f44:5dd8:c956::1' prefix='64'>
    <dhcp>
      <range start='fd2e:6f44:5dd8:c956::100' end='fd2e:6f44:5dd8:c956::150'/>
      <host id='00:03:00:01:52:54:00:55:d6:5c' name='master-0' ip='fd2e:6f44:5dd8:c956::130'/>
      <host id='00:03:00:01:52:54:00:47:77:b6' name='master-1' ip='fd2e:6f44:5dd8:c956::139'/>
      <host id='00:03:00:01:52:54:00:96:f0:40' name='master-2' ip='fd2e:6f44:5dd8:c956::142'/>
      <host id='00:03:00:01:52:54:00:18:c6:ff' name='worker-0' ip='fd2e:6f44:5dd8:c956::135'/>
    </dhcp>
  </ip>
  <dnsmasq:options>
    <dnsmasq:option value='dhcp-option=option6:dns-server,[fd00::]'/>
  </dnsmasq:options>
</network>
```

**Comment by 14rcole** [comment]
In that case, I'd agree that we can merge it.  @samvarankashyap we'll need to make a note in the release email that there may be unidentified bugs in libvirt (not because of this PR, just because the CI in general is down)

**Comment by samvarankashyap** [comment]
@14rcole Sure

**Comment by samvarankashyap** [comment]
[merge]

**Pull request merged**
