### PR TITLE
Make linchpin pull roles from ansible galaxy

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Quick question, 
did you happen to move all the roles?

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
All of these failures are due to resource conflicts, so I'm going to retrigger the tests tonight

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]
Just fixed some azure issues so this should be good now

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
> @14rcole Quick question,
> 
>     * did you happen to move all the roles?
The roles still exist inside of linchpin for now.  This adds the support for pulling roles externally but aside from the example role I created, I didn't touch anything
> 
>     * where are the roles currently hosted?
The role I created is hosted in a personal git repo. We'll work out more hosting eventually.  The current role is [here](https://github.com/14rcole/ansible-role-lp-dummy)
>
>       have you tried hosting it inside the current repository?
Yes, there's no way to do it with tags or with branches.  Each role will need to go in its own repository.  We can, however, use tags to version the roles moving forward.
> 
>     * how does this affect the integration tests?
The integration tests will be able to just pull the roles when they run `linchpin up`.  However, we will eventually be able to use fewer integration tests once we add molecule support
> 
>     * Are we following oasis standards ?
Not yet, the next step is to get the dummy role I created as an example up to standards and create a guide for moving the roles so that other people can help out

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
