### PR TITLE
Fix container release job

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
@samvarankashyap can you take a look?

**Comment by samvarankashyap** [comment]
@14rcole sure

**Comment by samvarankashyap** [comment]
@14rcole Can we merge this ??

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
