### PR TITLE
Release v1.8.0

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@14rcole Failed in psi environment. Will be fixing it.

**Comment by samvarankashyap** [comment]
Openstack credentials fixed. 
Beaker is failing due to authentication issues.

**Comment by samvarankashyap** [comment]
Fixed beaker credentials issue. Retesting on psi env

**Comment by samvarankashyap** [comment]
@14rcole 
Openshift bug with ansible k8s module. 
Disabling it by #1297 since its blocking our release. 
Once it's merged. We can rebase this PR and perform a release today.

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
