### PR TITLE
Make linchpin look in multiple locations for ansible galaxy roles

### LINKED ISSUE #1408: Linchpin nightly build fails due to "cannot find role: 14rcole.ansible_role_lp_dummy"

### PR DESCRIPTION
**Pull request by 14rcole**
Currently linchpin only looks in ~/.ansible/roles.  This expands the search area to all directories listed in `ansible-galaxy list`

Fixes #1408

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole Any update on this PR. 
#1407 is currently blocked on dummy tests and add_res_group filter not found.

**Comment by 14rcole** [comment]
@samvarankashyap This works everywhere except the integration test. I think I got it this time.  This will fix the dummy test, but the add_res_group filter should have been fixed by #1402.  Have you rebased since then?

**Comment by samvarankashyap** [comment]
@14rcole I believe I did rebase. However, I will re-confirm it.

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
