### PR TITLE
Release version 1.7.5

### PR DESCRIPTION
**Pull request by 14rcole**

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by 14rcole** [comment]
[test]

**Comment by p3ck** [comment]
@14rcole You don't have a centos7 container running in the JenkinsfileContainer jenkinsfile.  So the following will never work:
```
                        pipelineUtils.executeInContainer("cleanup-openstack", "centos7", "./config/Dockerfiles/cleanup-openstack.sh")
```

**Comment by 14rcole** [comment]
@p3ck I know, I'm trying to figure out the correct way to do it, but I've been putting the changes in #1133

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
@14rcole : Failing on ec2_eip , 
I think me may have hit quota for eip or it's disabled. 
You can disable the test if it is persistent.

**Comment by 14rcole** [comment]
@samvarankashyap sounds good.  it also looks like jenkins downstream isn't always triggering

**Comment by 14rcole** [comment]
[test]

**Comment by p3ck** [comment]
rather than blindly commenting test again and again you should look at the queue on the downstream jenkins.  You'll see you have 2 PR's queued multiple times (6 in the backlog)

**Comment by samvarankashyap** [comment]
@14rcole I have re-triggered the downstream tests 
https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin/1075/console 
seems like there are successful. 
You may merge the PR once they finish.

**Comment by 14rcole** [comment]
@samvarankashyap I had also  retriggered the build.  I'll do the release as soon as I get a success from one

**Comment by 14rcole** [comment]
Build https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin/1077/ passed, so I'm going to merge this

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
