### PR TITLE
Revert "Wrap IPv6 addresses on ansible_ssh_host fixes issue #1691"

### PR DESCRIPTION
**Pull request by yprokule**
This reverts commit efeca3827cdb2c981c145114cd55c44019b70627.

Wrapping IPv6 address in inventory break connectivity to the nodes

```yaml
node-0-0 hostname=node-0-0 ansible_ssh_host=[fd2e:6f44:5dd8::12b] ...
```

fails like
```yaml
node-0-0 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname [fd2e:6f44:5dd8::12b]: Name or service not known",
    "unreachable": true
}
```

Removing the quotes fixes the issue

```yaml
node-0-0 hostname=node-0-0 ansible_ssh_host=fd2e:6f44:5dd8::12b
```

```yaml
node-0-0 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

**Packages**
```
linchpin==2.0.3
ansible==2.9.13
```

### CODE REVIEW

**Comment by Dannyb48** [comment]
@abraverm @JunqiZhang0 could one of you guys review this?

**Comment by abraverm** [comment]
@yprokule , looks good to me, but please fix the linting issue

**Review by abraverm — APPROVED** [review]

**Pull request merged**
