### PR TITLE
VMware guest support

### PR DESCRIPTION
**Pull request by abraverm**

### CODE REVIEW

**Comment by abraverm** [comment]
[test]

**Comment by abraverm** [comment]
fixes  #990

**Comment by samvarankashyap** [comment]
@abraverm Do you have the testing infrastructure for VMware?
Is it possible to add integration tests to VMware provider?

**Comment by abraverm** [comment]
I used the [ESXi on libvirt][https://github.com/CentOS-PaaS-SIG/linchpin/pull/1035] to develop this provider (locally). The integration testing will require deploying ESXi and configuring it on libvirt prior of testing the provider. Its possible but I fear it won't be stable enough... I hope when we get enough traction with this module, we will able to get stable deployment internally and then integration testing would be simple.

**Comment by 14rcole** [comment]
This looks great.  If there's anything here to test besides the simple up and destroy that's covered by `general/01_general` in our tests, can you add the integration tests and simply set `providers.include: none`?  That way we'll have the tests available if we need to run them locally

**Comment by abraverm** [comment]
CI is generally failing, not related to the PR

@14rcole, shouldn't it be `providers.exclude: vmware` ?

**Comment by 14rcole** [comment]
@abraverm I didn't know if you had anything else you might need to test.  You don't technically need to exclude vmware from `01_general` because the tests won't be run until we add vmware (here)[https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/config/Dockerfiles/JenkinsfileContainer#L29-L116] but it's not a problem either

**Comment by abraverm** [comment]
awesome, I didn't know that. thanks!

**Comment by abraverm** [comment]
[merge]

**Pull request merged**
