### PR TITLE
use gitHubAPI to do the merge

### PR DESCRIPTION
**Pull request by p3ck**
This library gives us the merge commit so we can pass that
to the next job.

### CODE REVIEW

**Comment by p3ck** [comment]
@samvarankashyap Please let me know when we will have another PR that can be merged shortly after this one.  It's hard to test this without merging it in.  Maybe morning Tomorrow?

**Comment by samvarankashyap** [comment]
@p3ck we have #836 ready to merge .

**Comment by p3ck** [comment]
[merge]

**Comment by p3ck** [comment]
[merge]

**Pull request merged**
