### PR TITLE
Misc fixes

### LINKED ISSUE #397: Duffy allocation fails
using latest version from git I get the following failure when trying to bring up a duffy node.

 linchpin up duffy
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This 
feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is 
discouraged. The module documentation details page may explain more about this 
rationale.. This feature will be removed in a future release. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Included file '/usr/lib/python2.7/site-
packages/linchpin/provision/update_aws_cfn_outputs.yml' not found, however since this
 include is not explicitly marked as 'static: yes', we will try and include it 
dynamically later. In the future, this will be an error unless 'static: no' is used 
on the include task. If you do not want missing includes to be considered dynamic, 
use 'static: yes' on the include or set the global ansible.cfg options to make all 
includes static for tasks and/or handlers. This feature will be removed in version 
2.7. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
	to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry
Target 'duffy': TASK: duffy : Set cred path failed with error 'The conditional check 'creds_path == default_credentials_path' failed. The error was: error while evaluating conditional (creds_path == default_credentials_path): 'creds_path' is undefined

The error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/duffy/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# duffy puts its key by default in the user's home directory.
- name: "Set cred path"
  ^ here
'

using the following topology from lp_test_workspace:
---
topology_name: duffy1
resource_groups:
  - resource_group_name: duffy1
    resource_group_type: duffy
    resource_definitions:
      - type: duffy_node
        name: duffy
        version: 7
        arch: x86_64
        count: 1
    credentials: duffy.key

### PR DESCRIPTION
**Pull request by herlo**
Fixes #397 #389 #388 

Changes the default count for linchpin journal to 3, as that makes logical sense.

### CODE REVIEW

**Comment by herlo** [comment]
@p3ck I'm not experiencing the issue you are reporting. 

Running CentOS 7 and a python virtual environment, this succeeds for me with the topology from https://github.com/herlo/lp_test_workspace/blob/master/topologies/duffy.yml

**Comment by samvarankashyap** [comment]
@herlo : 
I could not find duffy.py ansible module in linchpin/provision/library. 
Is it accidentally deleted in one of the PRs ? or am i missing something ?
It might be the reason for @p3ck  error! .

**Comment by herlo** [comment]
Ah, good point. @p3ck might be interested that a symlink from the library
folder in https://github.com/CentOS-PaaS-SIG/duffy-ansible-module to the
linchpin/provision/library path in will do the trick. I also need to make
sure this is in the docs.

Thanks!

**Comment by p3ck** [comment]
@herlo is there not an install procedure for installing this module?

**Comment by herlo** [comment]
@p3ck No, there is not at this time. It was always thought that linchpin would eventually be broken into core and contributed modules. Time and other factors have prevented this from happening. 

The procedure is pretty straightforward though, and in general modules land in a library directory. According to ansible, modules live in a library path, which can be confiigured -- http://docs.ansible.com/ansible/latest/intro_configuration.html#library

If it's any consolation, Makefiles were going to be the direction for managing modules and the like. If updating that is of interest, please let me know

**Comment by herlo** [comment]
I should also mention, that the duffy module is something that most users will never encounter. Duffy lives in that small space of CentOS CI that most will likely never touch. Not that it couldn't change and become the best tool ever, but I don't foresee that as a thing. This, is the exact reason the duffy module was not included in linchpin.

**Pull request merged**
