### PR TITLE
Adjust validation so that 'type' does not create an error

### PR DESCRIPTION
**Pull request by 14rcole**
Solves #677

### CODE REVIEW

**Comment by herlo** [comment]
When the topology validates against the 'old' schema, it says so. 

`topology for target 'simple' is valid under old schema`

When the topology validates against the 'new' schema, it doesn't say so.

I'm not sure this is possible, but is there a way to say something like `'type' is old, use 'role'`? Or maybe suggest updating? Thoughts?

**Comment by 14rcole** [comment]
We can do that.  Old schema is guaranteed to use 'type' instead of 'role', right?

**Comment by 14rcole** [comment]
I can do that. I actually think that instead of printing out the message about replacing directives for every topology that validates only under the old schema, we should have the message print out at the end (only if some topologies validate under the old schema).  It looks cleaner that way

**Comment by 14rcole** [comment]
[merge]

**Pull request merged**
