### PR TITLE
Add support for beaker partitions in schema

### PR DESCRIPTION
**Pull request by p3ck**
Small update needed to support partition schema.

### CODE REVIEW

**Comment by p3ck** [comment]
fixes #1111

**Comment by p3ck** [comment]
[merge]

**Comment by samvarankashyap** [comment]
fixes #1111

**Comment by johnbieren** [comment]
From the beaker user guide:
type = type <!- required ->
should we change type to required? Or default it to type=part or something?

**Comment by p3ck** [comment]
> From the beaker user guide:
> type = type <!- required ->
> should we change type to required? Or default it to type=part or something?

The documentation doesn't match the code in beaker scheduler:
```
type = partition.getAttribute('type') or 'part'
```

**Comment by johnbieren** [comment]
oh, nice

**Pull request merged**
